In [65]:
import pandas as pd

In [69]:
df = pd.read_csv('Online_Course_Enrollment_Large_Messy.csv')
df.head(10)

,enrollment_id,student_name,age,gender,city,course_name,course_category,course_fee,payment_status,completion_status,discount_code,enrollment_month,enrollment_year,referral_source,device_type
0,ENR1001,Ramesh Kumar,24.0,NaN,ahemdabad,Network Security Essentials,CYBER SECURITY,₹8499,Failed,Incomplete,ALUMNI20,Jul,2023,Google Search,Desktop
1,ENR1002,Deepa Solanki,41.0,FEMALE,Puna,UI/UX Design Essentials,Web Dev,INR 8999,Paid,Completed,NaN,Jan,2024,Facebook Ad,mobile
2,ENR1003,Nikhil Trivedi,18.0,F,visakhapatnam,Business Intelligence Reporting,business Anaytics,Rs.6999,Paid,Completed,FLASHSALE,Mar,2023,College Partnership,NaN
3,ENR1004,Smita Jadhav,42.0,Female,chandigarh,Multi-Cloud Architecture,Cloud Computing,₹17499,Paid,Completed,NaN,Dec,2024,College Partnership,MOBILE
4,ENR1005,Ajay Goswami,22.0,female,Jaipuur,Business Intelligence Reporting,business Anaytics,INR. 6999,Pending,Incomplete,NaN,Oct,2024,Instagram Ad,Tablet
5,ENR1006,Saritha Mehta,34.0,Male,Kolkata,Ethical Hacking Bootcamp,CyberSecurity,Rs 13999,Failed,Incomplete,NEW20,Jul,2023,Google Search,Desktop
6,ENR1007,Manoj Naik,32.0,Female,Dilli,Azure Fundamentals,Cloud computing,11499,Paid,Incomplete,ALUMNI20,Sep,2024,YouTube Ad,Mobile
7,ENR1008,NaN,31.0,NaN,mumbai,Google Cloud Essentials,cloud computing,Rs. 10999,Failed,Incomplete,FLASHSALE,Sep,2023,Google Search,Mobile
8,ENR1009,NaN,24.0,F,Kolkata,Multi-Cloud Architecture,CLOUD COMPUTING,INR 17499,Paid,Incomplete,STUDENT15,Apr,2023,College Partnership,desktop
9,ENR1186,Kavya Krishnan,37.0,NaN,Vizag,Deep Learning Essentials,Artificial Intelligence,₹18499,Failed,Incomplete,CORP50,Sep,2024,Google Search,NaN

In [70]:
df.shape

(540, 15)

In [71]:
df.columns

Index(['enrollment_id', 'student_name', 'age', 'gender', 'city', 'course_name',
       'course_category', 'course_fee', 'payment_status', 'completion_status',
       'discount_code', 'enrollment_month', 'enrollment_year',
       'referral_source', 'device_type'],
      dtype='object')

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 540 entries, 0 to 539
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   enrollment_id      540 non-null    object
 1   student_name       490 non-null    object
 2   age                513 non-null    float64
 3   gender             496 non-null    object
 4   city               540 non-null    object
 5   course_name        540 non-null    object
 6   course_category    540 non-null    object
 7   course_fee         540 non-null    object
 8   payment_status     540 non-null    object
 9   completion_status  540 non-null    object
 10  discount_code      306 non-null    object
 11  enrollment_month   540 non-null    object
 12  enrollment_year    540 non-null    int64
 13  referral_source    531 non-null    object
 14  device_type        478 non-null    object
dtypes: float64(1), int64(1), object(13)
memory usage: 63.4+ KB

In [73]:
df.isnull().sum()

enrollment_id          0
student_name          50
age                   27
gender                44
city                   0
course_name            0
course_category        0
course_fee             0
payment_status         0
completion_status      0
discount_code        234
enrollment_month       0
enrollment_year        0
referral_source        9
device_type           62
dtype: int64

## Data Cleaning Process

In [74]:
df['city'] = df['city'].str.strip().str.title()
df['city'].head()

0        Ahemdabad
1             Puna
2    Visakhapatnam
3       Chandigarh
4          Jaipuur
Name: city, dtype: object

In [75]:
df['course_category'] = (df['course_category'].str.strip().str.title())
df['course_category'].head()

0       Cyber Security
1              Web Dev
2    Business Anaytics
3      Cloud Computing
4    Business Anaytics
Name: course_category, dtype: object

In [76]:
df['course_fee'] = (
    df['course_fee']
    .astype(str)
    .str.replace('₹','', regex=False)
    .str.replace('Rs.','', regex=False)
    .str.replace('INR','', regex=False)
    .str.replace('.','', regex=False)
    .str.strip()
)


df['course_fee'] = pd.to_numeric(df['course_fee'],errors='coerce')
df[['course_fee']].head()

   course_fee
0      8499.0
1      8999.0
2      6999.0
3     17499.0
4      6999.0

In [77]:
# Handling Missing Student Names
df['student_name'] = (df['student_name'].fillna('Unknown Student'))

# Handling Missing Discount Codes
df['discount_code'] = (df['discount_code'].fillna('No Discount'))

df[['student_name','discount_code']].head(10)

      student_name discount_code
0     Ramesh Kumar      ALUMNI20
1    Deepa Solanki   No Discount
2   Nikhil Trivedi     FLASHSALE
3     Smita Jadhav   No Discount
4     Ajay Goswami   No Discount
5    Saritha Mehta         NEW20
6       Manoj Naik      ALUMNI20
7  Unknown Student     FLASHSALE
8  Unknown Student     STUDENT15
9   Kavya Krishnan        CORP50

In [78]:
df.duplicated().sum()

np.int64(40)

In [79]:
df = df.drop_duplicates()
len(df)

500

## Revenue Analysis

In [80]:
# Creating Gross Fee

df['gross_fee'] = df['course_fee']
df[['course_fee','gross_fee']].head()

   course_fee  gross_fee
0      8499.0     8499.0
1      8999.0     8999.0
2      6999.0     6999.0
3     17499.0    17499.0
4      6999.0     6999.0

In [95]:
# Revenue Summary

print("Total Gross Revenue:", df["gross_fee"].sum())
print("Total Valid Revenue:",df["valid_fee_collected"].sum())

Total Gross Revenue: 3894091.0
Total Valid Revenue: 1035368.0

In [81]:
# Creating Valid Fee Collected

# Revenue counts only when:
# Payment = Paid
# Completion = Completed

df['valid_fee_collected'] = 0
df.loc[(df['payment_status'] == 'Paid') &(df['completion_status'] == 'Completed'),'valid_fee_collected'] = df['gross_fee']

df[['enrollment_id','payment_status','completion_status','gross_fee','valid_fee_collected']].head()

,enrollment_id,payment_status,completion_status,gross_fee,valid_fee_collected
0,ENR1001,Failed,Incomplete,8499.0,0.0
1,ENR1002,Paid,Completed,8999.0,8999.0
2,ENR1003,Paid,Completed,6999.0,6999.0
3,ENR1004,Paid,Completed,17499.0,17499.0
4,ENR1005,Pending,Incomplete,6999.0,0.0

In [82]:
# Failed Payment Enrollments

failed_payments = df[df['payment_status'] == 'Failed']
print('Failed Payments:', len(failed_payments))

failed_payments[['enrollment_id','student_name','course_name','gross_fee']].head()

Failed Payments: 169

   enrollment_id       student_name                  course_name  gross_fee
0        ENR1001       Ramesh Kumar  Network Security Essentials     8499.0
5        ENR1006      Saritha Mehta     Ethical Hacking Bootcamp        NaN
7        ENR1008    Unknown Student      Google Cloud Essentials    10999.0
9        ENR1186     Kavya Krishnan     Deep Learning Essentials    18499.0
11       ENR1012  Sandeep Chaudhary         ML with Scikit-Learn        NaN

In [83]:
# Incomplete Course Enrollments

incomplete_courses = df[df['completion_status'] == 'Incomplete']
print('Incomplete Enrollments:', len(incomplete_courses))

incomplete_courses[['enrollment_id','student_name','course_name']].head()

Incomplete Enrollments: 339

  enrollment_id     student_name                      course_name
0       ENR1001     Ramesh Kumar      Network Security Essentials
4       ENR1005     Ajay Goswami  Business Intelligence Reporting
5       ENR1006    Saritha Mehta         Ethical Hacking Bootcamp
6       ENR1007       Manoj Naik               Azure Fundamentals
7       ENR1008  Unknown Student          Google Cloud Essentials

In [84]:
#  Paid But Incomplete

paid_incomplete = df[(df['payment_status'] == 'Paid') &(df['completion_status'] == 'Incomplete')]
print('Paid But Incomplete:', len(paid_incomplete))

paid_incomplete[['student_name','course_name','gross_fee']].head()

Paid But Incomplete: 94

       student_name                 course_name  gross_fee
6        Manoj Naik          Azure Fundamentals    11499.0
8   Unknown Student    Multi-Cloud Architecture    17499.0
12     Manish Kumar             NLP with Python        NaN
14    Sarika Murthy    Multi-Cloud Architecture    17499.0
21     Sarika Gowda  Content Marketing Strategy     3499.0

In [85]:
# Payment Failed OR Course Incomplete

problem_enrollments = df[(df['payment_status'] == 'Failed') |(df['completion_status'] == 'Incomplete')]
print('Problem Enrollments:', len(problem_enrollments))

problem_enrollments.head()

Problem Enrollments: 339

,enrollment_id,student_name,age,gender,city,course_name,course_category,course_fee,payment_status,completion_status,discount_code,enrollment_month,enrollment_year,referral_source,device_type,gross_fee,valid_fee_collected
0,ENR1001,Ramesh Kumar,24.0,NaN,Ahemdabad,Network Security Essentials,Cyber Security,8499.0,Failed,Incomplete,ALUMNI20,Jul,2023,Google Search,Desktop,8499.0,0.0
4,ENR1005,Ajay Goswami,22.0,female,Jaipuur,Business Intelligence Reporting,Business Anaytics,6999.0,Pending,Incomplete,No Discount,Oct,2024,Instagram Ad,Tablet,6999.0,0.0
5,ENR1006,Saritha Mehta,34.0,Male,Kolkata,Ethical Hacking Bootcamp,Cybersecurity,NaN,Failed,Incomplete,NEW20,Jul,2023,Google Search,Desktop,NaN,0.0
6,ENR1007,Manoj Naik,32.0,Female,Dilli,Azure Fundamentals,Cloud Computing,11499.0,Paid,Incomplete,ALUMNI20,Sep,2024,YouTube Ad,Mobile,11499.0,0.0
7,ENR1008,Unknown Student,31.0,NaN,Mumbai,Google Cloud Essentials,Cloud Computing,10999.0,Failed,Incomplete,FLASHSALE,Sep,2023,Google Search,Mobile,10999.0,0.0

In [86]:
# High Value Failed Enrollments Above 5000

high_value_failed = df[(df['payment_status'] == 'Failed') &(df['gross_fee'] > 5000)]
print('High Value Failed Enrollments:', len(high_value_failed))

high_value_failed[['student_name','course_name','gross_fee']].head()

High Value Failed Enrollments: 107

       student_name                   course_name  gross_fee
0      Ramesh Kumar   Network Security Essentials     8499.0
7   Unknown Student       Google Cloud Essentials    10999.0
9    Kavya Krishnan      Deep Learning Essentials    18499.0
17   Lakshmi Sharma  Data Engineering with Python    13499.0
26  Revathi Agarwal   Cyber Security Fundamentals     9999.0

In [87]:
# Filter Students From Selected Cities

selected_cities = df[df['city'].isin(['Chennai','Bangalore','Coimbatore'])]
print('Selected City Enrollments:', len(selected_cities))

selected_cities[['student_name','city']].head()

Selected City Enrollments: 39

       student_name        city
10  Unknown Student  Coimbatore
15       Rohit Shah  Coimbatore
17   Lakshmi Sharma  Coimbatore
18    Tarun Goswami   Bangalore
20   Vivek Krishnan  Coimbatore

In [88]:
# Course Fee Between 3000 and 10000

fee_range = df[(df['gross_fee'] >= 3000) &(df['gross_fee'] <= 10000)]
print('Enrollments Between 3000 and 10000:', len(fee_range))

fee_range[['student_name','gross_fee']].head()

Enrollments Between 3000 and 10000: 238

       student_name  gross_fee
0      Ramesh Kumar     8499.0
1     Deepa Solanki     8999.0
2    Nikhil Trivedi     6999.0
4      Ajay Goswami     6999.0
10  Unknown Student     4999.0

In [89]:
# Filter Enrollments That Used a Discount Code

discount_enrollments = df[df['discount_code'] != 'No Discount']
print('Discount Code Enrollments:', len(discount_enrollments))

discount_enrollments[['student_name','discount_code']].head()

Discount Code Enrollments: 288

      student_name discount_code
0     Ramesh Kumar      ALUMNI20
2   Nikhil Trivedi     FLASHSALE
5    Saritha Mehta         NEW20
6       Manoj Naik      ALUMNI20
7  Unknown Student     FLASHSALE

In [90]:
# Discount Code Enrollments With Zero Revenue

discount_zero_revenue = df[(df['discount_code'] != 'No Discount') &(df['valid_fee_collected'] == 0)]
print('Discount But No Revenue:', len(discount_zero_revenue))

discount_zero_revenue[['student_name','discount_code','valid_fee_collected']].head()

Discount But No Revenue: 200

      student_name discount_code  valid_fee_collected
0     Ramesh Kumar      ALUMNI20                  0.0
5    Saritha Mehta         NEW20                  0.0
6       Manoj Naik      ALUMNI20                  0.0
7  Unknown Student     FLASHSALE                  0.0
8  Unknown Student     STUDENT15                  0.0

In [104]:
# Completion Status Summary

df["completion_status"].value_counts()

completion_status
Incomplete    339
Completed     161
Name: count, dtype: int64

In [97]:
# Payment Status Summary

df["payment_status"].value_counts()

payment_status
Paid       255
Failed     169
Pending     76
Name: count, dtype: int64

In [101]:
# Top Revenue Generating Courses

df.groupby("course_name")["valid_fee_collected"].sum().sort_values(ascending=False).head(10)

course_name
Deep Learning Essentials           73996.0
Django for Beginners               63992.0
Business Intelligence Reporting    62991.0
Power BI Analytics                 59992.0
Python for Data Science            53994.0
Digital Marketing Pro              41993.0
Cyber Security Fundamentals        39996.0
AWS Cloud Practitioner             38997.0
Multi-Cloud Architecture           34998.0
Advanced Excel Dashboarding        34990.0
Name: valid_fee_collected, dtype: float64

In [91]:
# Course Category Issue Count

df['course_category'].value_counts()

course_category
Data Science               52
Devops                     46
Digital Marketing          40
Programming                34
Machine Learning           32
Web Development            32
Business Analytics         32
Cyber Security             32
Artificial Intelligence    32
Cloud Computing            27
Programing                 22
Cybersecurity              15
Web Dev                    14
Digitall Marketing         11
Artifical Intelligence      9
Cloud Compuing              9
Digital Markting            8
Business Anaytics           8
Busniess Analytics          8
Machne Learning             7
Ai                          7
Datascience                 6
Cloud Compuuting            6
Dev Ops                     6
Ml                          5
Name: count, dtype: int64

In [92]:
# City Issue Count

df['city'].value_counts().head(20)

city
Patna         24
Lucknow       20
Indore        19
Coimbatore    18
Ranchi        18
Surat         17
Chandigarh    16
Pune          16
Vizag         15
Delhi         15
Nagpur        15
Chennai       14
Mumbai        13
Kolkata       13
Mysore        13
Bhopal        12
Baroda        12
Ahemdabad     12
Noida         12
Kochi         11
Name: count, dtype: int64